const productos = [
    {
        id: 1,
        productName: "Banana",
        price: 500,
        quanty: 1,
        img: "media/Banana.png",
    },
    {
        id: 2,
        productName: "Kiwi",
        price: 500,
        quanty: 1,
        img: "/media/Kiwi.png",
    }, 
    {
        id: 3,
        productName: "Lechuga",
        price: 500,
        quanty: 1,
        img: "media/Lechuga.png",
    }, 
    {
        id: 4,
        productName: "Limon",
        price: 500,
        quanty: 1,
        img: "media/Limon.png",
    }, 
    {
        id: 5,
        productName: "Morron",
        price: 500,
        quanty: 1,
        img: "media/Morron.png",
    }, 
    {
        id: 6,
        productName: "Papa",
        price: 500,
        quanty: 1,
        img: "media/Papa.png",
    }, 
    {
        id: 7,
        productName: "Pepino",
        price: 500,
        quanty: 1,
        img: "media/Pepino.png",
    }, 
    {
        id: 8,
        productName: "Tomate",
        price: 500,
        quanty: 1,
        img: "media/Tomate.png",
    }, 
]
